# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import payments_bills_service_pb2 as payments__bills__service__pb2


class ChargesStub(object):
  """message Invoice {
  //completar con la info de stripe
  }

  Service to manage payments
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateChargeToCustomer = channel.unary_unary(
        '/payments_bills_service.Charges/CreateChargeToCustomer',
        request_serializer=payments__bills__service__pb2.ChargeObject.SerializeToString,
        response_deserializer=payments__bills__service__pb2.GetByIdCharge.FromString,
        )
    self.CreateChargeToSource = channel.unary_unary(
        '/payments_bills_service.Charges/CreateChargeToSource',
        request_serializer=payments__bills__service__pb2.ChargeObject.SerializeToString,
        response_deserializer=payments__bills__service__pb2.GetByIdCharge.FromString,
        )
    self.GetChargeById = channel.unary_unary(
        '/payments_bills_service.Charges/GetChargeById',
        request_serializer=payments__bills__service__pb2.GetByIdCharge.SerializeToString,
        response_deserializer=payments__bills__service__pb2.ChargeObject.FromString,
        )
    self.GetChargeList = channel.unary_stream(
        '/payments_bills_service.Charges/GetChargeList',
        request_serializer=payments__bills__service__pb2.ListRequest.SerializeToString,
        response_deserializer=payments__bills__service__pb2.ChargeObject.FromString,
        )
    self.EditChargeById = channel.unary_unary(
        '/payments_bills_service.Charges/EditChargeById',
        request_serializer=payments__bills__service__pb2.GetByIdCharge.SerializeToString,
        response_deserializer=payments__bills__service__pb2.ChargeObject.FromString,
        )


class ChargesServicer(object):
  """message Invoice {
  //completar con la info de stripe
  }

  Service to manage payments
  """

  def CreateChargeToCustomer(self, request, context):
    """Create a charge object to charge a credit or a debit card with the customer id
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateChargeToSource(self, request, context):
    """Create a charge object to charge a credit or a debit card with a source stripe token
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetChargeById(self, request, context):
    """Get  the details of a charge that has previously been created
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetChargeList(self, request, context):
    """Returns a list of charges you’ve previously created
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def EditChargeById(self, request, context):
    """Updates the specified charge by setting the values of the parameters passed
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ChargesServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateChargeToCustomer': grpc.unary_unary_rpc_method_handler(
          servicer.CreateChargeToCustomer,
          request_deserializer=payments__bills__service__pb2.ChargeObject.FromString,
          response_serializer=payments__bills__service__pb2.GetByIdCharge.SerializeToString,
      ),
      'CreateChargeToSource': grpc.unary_unary_rpc_method_handler(
          servicer.CreateChargeToSource,
          request_deserializer=payments__bills__service__pb2.ChargeObject.FromString,
          response_serializer=payments__bills__service__pb2.GetByIdCharge.SerializeToString,
      ),
      'GetChargeById': grpc.unary_unary_rpc_method_handler(
          servicer.GetChargeById,
          request_deserializer=payments__bills__service__pb2.GetByIdCharge.FromString,
          response_serializer=payments__bills__service__pb2.ChargeObject.SerializeToString,
      ),
      'GetChargeList': grpc.unary_stream_rpc_method_handler(
          servicer.GetChargeList,
          request_deserializer=payments__bills__service__pb2.ListRequest.FromString,
          response_serializer=payments__bills__service__pb2.ChargeObject.SerializeToString,
      ),
      'EditChargeById': grpc.unary_unary_rpc_method_handler(
          servicer.EditChargeById,
          request_deserializer=payments__bills__service__pb2.GetByIdCharge.FromString,
          response_serializer=payments__bills__service__pb2.ChargeObject.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'payments_bills_service.Charges', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class CustomersStub(object):
  """Service to manage customers
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetCustomerById = channel.unary_unary(
        '/payments_bills_service.Customers/GetCustomerById',
        request_serializer=payments__bills__service__pb2.GetByIdCharge.SerializeToString,
        response_deserializer=payments__bills__service__pb2.CustomerObject.FromString,
        )
    self.GetCustomesList = channel.unary_stream(
        '/payments_bills_service.Customers/GetCustomesList',
        request_serializer=payments__bills__service__pb2.ListRequest.SerializeToString,
        response_deserializer=payments__bills__service__pb2.ChargeObject.FromString,
        )
    self.CreateCustomer = channel.unary_unary(
        '/payments_bills_service.Customers/CreateCustomer',
        request_serializer=payments__bills__service__pb2.ChargeObject.SerializeToString,
        response_deserializer=payments__bills__service__pb2.GetByIdCharge.FromString,
        )
    self.DeleteCustomer = channel.unary_unary(
        '/payments_bills_service.Customers/DeleteCustomer',
        request_serializer=payments__bills__service__pb2.GetByIdCharge.SerializeToString,
        response_deserializer=payments__bills__service__pb2.ChargeObject.FromString,
        )


class CustomersServicer(object):
  """Service to manage customers
  """

  def GetCustomerById(self, request, context):
    """Get the details of a Customer 
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetCustomesList(self, request, context):
    """Get a list of the customers previously created
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateCustomer(self, request, context):
    """Create a new customer
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteCustomer(self, request, context):
    """Delete a customer previously created
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CustomersServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetCustomerById': grpc.unary_unary_rpc_method_handler(
          servicer.GetCustomerById,
          request_deserializer=payments__bills__service__pb2.GetByIdCharge.FromString,
          response_serializer=payments__bills__service__pb2.CustomerObject.SerializeToString,
      ),
      'GetCustomesList': grpc.unary_stream_rpc_method_handler(
          servicer.GetCustomesList,
          request_deserializer=payments__bills__service__pb2.ListRequest.FromString,
          response_serializer=payments__bills__service__pb2.ChargeObject.SerializeToString,
      ),
      'CreateCustomer': grpc.unary_unary_rpc_method_handler(
          servicer.CreateCustomer,
          request_deserializer=payments__bills__service__pb2.ChargeObject.FromString,
          response_serializer=payments__bills__service__pb2.GetByIdCharge.SerializeToString,
      ),
      'DeleteCustomer': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteCustomer,
          request_deserializer=payments__bills__service__pb2.GetByIdCharge.FromString,
          response_serializer=payments__bills__service__pb2.ChargeObject.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'payments_bills_service.Customers', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class SuscriptionStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetSuscriptionById = channel.unary_unary(
        '/payments_bills_service.Suscription/GetSuscriptionById',
        request_serializer=payments__bills__service__pb2.GetByIdCharge.SerializeToString,
        response_deserializer=payments__bills__service__pb2.ChargeObject.FromString,
        )
    self.GetSuscriptionList = channel.unary_stream(
        '/payments_bills_service.Suscription/GetSuscriptionList',
        request_serializer=payments__bills__service__pb2.ListRequest.SerializeToString,
        response_deserializer=payments__bills__service__pb2.ChargeObject.FromString,
        )
    self.CreateSuscription = channel.unary_unary(
        '/payments_bills_service.Suscription/CreateSuscription',
        request_serializer=payments__bills__service__pb2.ChargeObject.SerializeToString,
        response_deserializer=payments__bills__service__pb2.GetByIdCharge.FromString,
        )
    self.CancelSuscription = channel.unary_unary(
        '/payments_bills_service.Suscription/CancelSuscription',
        request_serializer=payments__bills__service__pb2.GetByIdCharge.SerializeToString,
        response_deserializer=payments__bills__service__pb2.ChargeObject.FromString,
        )
    self.UpdateSuscription = channel.unary_unary(
        '/payments_bills_service.Suscription/UpdateSuscription',
        request_serializer=payments__bills__service__pb2.GetByIdCharge.SerializeToString,
        response_deserializer=payments__bills__service__pb2.ChargeObject.FromString,
        )


class SuscriptionServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetSuscriptionById(self, request, context):
    """Get the details of a suscription
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetSuscriptionList(self, request, context):
    """Get a listo of the descriptions previously created
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateSuscription(self, request, context):
    """Create a new suscription
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CancelSuscription(self, request, context):
    """Cancel a suscription
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateSuscription(self, request, context):
    """update a suscription
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SuscriptionServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetSuscriptionById': grpc.unary_unary_rpc_method_handler(
          servicer.GetSuscriptionById,
          request_deserializer=payments__bills__service__pb2.GetByIdCharge.FromString,
          response_serializer=payments__bills__service__pb2.ChargeObject.SerializeToString,
      ),
      'GetSuscriptionList': grpc.unary_stream_rpc_method_handler(
          servicer.GetSuscriptionList,
          request_deserializer=payments__bills__service__pb2.ListRequest.FromString,
          response_serializer=payments__bills__service__pb2.ChargeObject.SerializeToString,
      ),
      'CreateSuscription': grpc.unary_unary_rpc_method_handler(
          servicer.CreateSuscription,
          request_deserializer=payments__bills__service__pb2.ChargeObject.FromString,
          response_serializer=payments__bills__service__pb2.GetByIdCharge.SerializeToString,
      ),
      'CancelSuscription': grpc.unary_unary_rpc_method_handler(
          servicer.CancelSuscription,
          request_deserializer=payments__bills__service__pb2.GetByIdCharge.FromString,
          response_serializer=payments__bills__service__pb2.ChargeObject.SerializeToString,
      ),
      'UpdateSuscription': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateSuscription,
          request_deserializer=payments__bills__service__pb2.GetByIdCharge.FromString,
          response_serializer=payments__bills__service__pb2.ChargeObject.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'payments_bills_service.Suscription', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
